### ISSUE TITLE
Not scanning

### ISSUE THREAD

**Issue by dqmn** [MCServerScout/Discord-Bot#43]
**Describe the bug**
Prints out some ip ranges in the console, than prints out "queue is empty, sleeping" over and over.

**To Reproduce**
Run the scanner as root on WSL

**Expected behavior**
Well, fill the queue with ips

**Screenshots**
![image](https://github.com/MCServerScout/Discord-Bot/assets/127377373/e8f6286e-0a18-4c7b-b9b6-2e07d2152756)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2, WSL

**Comment by Pilot1782** [comment]
As of the latest commit this issue should be solved
