### ISSUE TITLE
help

### ISSUE THREAD

**Issue by max2007killer** [MCServerScout/Discord-Bot#50]
masscan-master>make
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
Makefile:16: pipe: No error
fatal: not a git repository (or any of the parent directories): .git
cc -g -ggdb    -Wall -O2 -c src/crypto-base64.c -o tmp/crypto-base64.o
process_begin: CreateProcess(NULL, cc -g -ggdb -Wall -O2 -c src/crypto-base64.c -o tmp/crypto-base64.o, ...) failed.
make (e=2): ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы.
make: *** [Makefile:109: tmp/crypto-base64.o] Error 2

**Comment by Pilot1782** [comment]
This is an issue with [masscan](https://github.com/robertdavidgraham/masscan/issues) they will be better suited to help you.

**Comment by max2007killer** [comment]
ok
